spring.application.name=projectManagementPlatform
spring.datasource.url=jdbc:postgresql://localhost:5432/devinfo
spring.datasource.username=devinfo
spring.datasource.password=devinfo

spring.jpa.hibernate.ddl-auto=update
